- hostProviders/aws/pom.xml
- hostProviders/aws/src/main/java/com/ibm/spectrum/aws/AwsImpl.java
- hostProviders/aws/src/main/java/com/ibm/spectrum/aws/client/AWSClient.java
- hostProviders/aws/src/main/java/com/ibm/spectrum/model/AwsMachine.java
- hostProviders/aws/src/main/java/com/ibm/spectrum/model/AwsRequest.java
- hostProviders/aws/src/main/java/com/ibm/spectrum/model/AwsTemplate.java
- hostProviders/aws/src/main/java/com/ibm/spectrum/util/AwsUtil.java
/kind feature
(https://github.ibm.com/platformcomputing/lsf-tracker/issues/2614)
> [main] AWS EC2 Fleet API support

- hostProviders/aws/src/main/java/com/ibm/spectrum/aws/client/AWSClient.java
Fixes #
https://github.ibm.com/platformcomputing/lsf-tracker/issues/2699
Refine the log messages.
```
> lsf-tracker#2699 refine log messages

- hostProviders/aws/src/main/java/com/ibm/spectrum/util/AwsUtil.java
- hostProviders/aws/src/main/java/log4j2.xml
Fixes #
https://github.ibm.com/platformcomputing/lsf-tracker/issues/2699
remove redundant log messages and enlarge logfile size to 1G
```
> remove redundant logs and enlarge logfile size

- hostProviders/aws/pom.xml
- hostProviders/aws/src/main/java/com/ibm/spectrum/aws/AwsImpl.java
- hostProviders/aws/src/main/java/com/ibm/spectrum/aws/client/AWSClient.java
- hostProviders/aws/src/main/java/com/ibm/spectrum/model/AwsMachine.java
- hostProviders/aws/src/main/java/com/ibm/spectrum/model/AwsRequest.java
- hostProviders/aws/src/main/java/com/ibm/spectrum/model/AwsTemplate.java
- hostProviders/aws/src/main/java/com/ibm/spectrum/util/AwsUtil.java
- hostProviders/aws/src/main/java/log4j2.xml
Fixes #
merge main to 10.1.0
```
> merge main to 10.1.0

- README.md
> Update Json format

- hostProviders/ibmcloudgen2/postprovision/lsf/example_user_data.sh
Cleanup
N/A
IBM VPC instance metadata service has changed and sample code will no longer function.
> Remove broken metadata query code from IBMCloud sample user_data.sh

- hostProviders/aws/src/main/java/com/ibm/spectrum/util/AwsUtil.java
- hostProviders/ibmcloudgen2/scripts/nextgen_return_request.py
- hostProviders/ibmcloudgen2/scripts/nextgen_utils.py
/kind feature
https://github.ibm.com/platformcomputing/lsf-tracker/issues/3024
merge code to main branch
```
> enhance file recovery remove empty file when loading and writing (#30)

- hostProviders/ibmcloudgen2/scripts/nextgen_rc_config.py
- hostProviders/ibmcloudgen2/scripts/vpc_vm_dns.py
> support config ApiEndPoints for IBM Cloud Gen2

- hostProviders/ibmcloudgen2/scripts/vpc_vm_dns.py
Fixes #
https://github.ibm.com/platformcomputing/hpccloud-tracker/issues/18
```
> hpccloud-tracker#18

- hostProviders/google/src/main/java/com/ibm/spectrum/gcloud/GcloudImpl.java
bug
Fixes #
https://github.ibm.com/platformcomputing/lsf-L3-tracker/issues/875
Log message bug.
```
> [main] refine log message

- hostProviders/google/src/main/java/com/ibm/spectrum/gcloud/GcloudImpl.java
bug
Fixes #
https://github.ibm.com/platformcomputing/lsf-L3-tracker/issues/875
Fix log message.
```
> refine log message

- hostProviders/google/src/main/java/com/ibm/spectrum/gcloud/GcloudImpl.java
- hostProviders/oracle/README.md
> Add oracle folder

- hostProviders/aws/pom.xml
- hostProviders/azure/pom.xml
- hostProviders/cyclecloud/pom.xml
- hostProviders/google/pom.xml
- hostProviders/openshift/pom.xml
design
Fixes #
Update 3rd party jar version
```
> Update 3rd party jar version

- hostProviders/aws/pom.xml
- hostProviders/azure/pom.xml
- hostProviders/cyclecloud/pom.xml
- hostProviders/google/pom.xml
- hostProviders/openshift/pom.xml
> [10.1.0] Update 3rd party jar version

- hostProviders/openshift/pom.xml
- hostProviders/openshift/src/main/java/com/ibm/spectrum/oc/client/Client.java
- hostProviders/openshift/src/main/java/com/ibm/spectrum/oc/util/Util.java
Fixes #
update k8s client java to 16.0.3
```
> [main] update k8s client java to 16.0.3

- hostProviders/openshift/pom.xml
- hostProviders/openshift/src/main/java/com/ibm/spectrum/oc/client/Client.java
- hostProviders/openshift/src/main/java/com/ibm/spectrum/oc/util/Util.java
Fixes #
update k8s client java to 16.0.3
```
> update k8s client java to 16.0.3

- hostProviders/aws/postprovision/lsf/example_user_data.sh
- hostProviders/azure/postprovision/lsf/example_user_data.sh
- hostProviders/cyclecloud/postprovision/lsf/example_user_data.sh
- hostProviders/ibmcloudgen2/postprovision/lsf/example_user_data.sh
- hostProviders/openstack/postprovision/lsf/example_user_data.sh
design
Fixes #
https://github.ibm.com/platformcomputing/lsf-tracker/issues/3307
Need install patch#601849 and then can use the new lsfd.service.
```
> [main] lsf-tracker#3307 install LSF as a service and startup

- hostProviders/aws/postprovision/lsf/example_user_data.sh
- hostProviders/azure/postprovision/lsf/example_user_data.sh
- hostProviders/cyclecloud/postprovision/lsf/example_user_data.sh
- hostProviders/ibmcloudgen2/postprovision/lsf/example_user_data.sh
- hostProviders/openstack/postprovision/lsf/example_user_data.sh
design
Fixes #
https://github.ibm.com/platformcomputing/lsf-tracker/issues/3307
Need install patch#601849 and then can use the new lsfd.service.
```
> lsf-tracker#3307 install LSF as a service and startup

- hostProviders/azure/pom.xml
design
Fixes #
Fix: Denial of Service in Connect2id Nimbus JOSE+JWT
Upgrade com.nimbusds:nimbus-jose-jwt to version 9.37.2 or later
```
> [main] upgrade nimbus-jose-jwt to 9.37.2

- hostProviders/azure/pom.xml
design
Fixes #
Fix: Denial of Service in Connect2id Nimbus JOSE+JWT
Upgrade com.nimbusds:nimbus-jose-jwt to version 9.37.2 or later
```
> upgrade nimbus-jose-jwt to 9.37.2

- hostProviders/aws/src/main/java/com/ibm/spectrum/constant/AwsConst.java
feature
Fixes #
https://github.ibm.com/platformcomputing/lsf-L3-tracker/issues/1112
Support AWS "Initiate Spot Instance Interruption" experiment.
```
> add instance-terminated-by-experiment

- hostProviders/aws/src/main/java/com/ibm/spectrum/constant/AwsConst.java
feature
Fixes #
https://github.ibm.com/platformcomputing/lsf-L3-tracker/issues/1112
Support "Initiate Spot Instance Interruption" experiment.
```
> [10.1.0] add instance-terminated-by-experiment

- hostProviders/aws/src/main/java/com/ibm/spectrum/aws/client/AWSClient.java
bug
Fixes #
Remove sample aws sec output
```
> remove sample aws sec

- hostProviders/aws/src/main/java/com/ibm/spectrum/aws/client/AWSClient.java
- hostProviders/aws/src/main/java/com/ibm/spectrum/model/AwsConfig.java
feature
Fixes # https://github.ibm.com/platformcomputing/lsf-tracker/issues/3798
Merge Sym AWS_ENDPOINT_URL.
```
> support AWS_ENDPOINT_URL

- hostProviders/aws/src/main/java/com/ibm/spectrum/aws/client/AWSClient.java
- hostProviders/aws/src/main/java/com/ibm/spectrum/model/AwsConfig.java
feature
Fixes # https://github.ibm.com/platformcomputing/lsf-tracker/issues/3798
Merge Sym AWS_ENDPOINT_URL.
```
> [main] support AWS_ENDPOINT_URL

- hostProviders/aws/pom.xml
- hostProviders/azure/pom.xml
- hostProviders/google/pom.xml
- hostProviders/google/src/main/java/com/ibm/spectrum/gcloud/client/GcloudClient.java
> Update RC API Plugins for Google and AWS

- hostProviders/ibmcloudgen2/scripts/nextgen_rc_config.py
- hostProviders/ibmcloudgen2/scripts/vpc_vm_dns.py
Feature: https://github.ibm.com/platformcomputing/lsf-tracker/issues/3890
Fixes #
```
> add crn and volumeprofile to ibmcloudgen2 to allow encryption key

- hostProviders/azure/pom.xml
- hostProviders/azure/src/main/java/com/ibm/spectrum/model/AzureRequest.java
> Azure API update from 1.0.0 to 1.41.4

- hostProviders/azure/pom.xml
- hostProviders/azure/src/main/java/com/ibm/spectrum/model/AzureRequest.java
> update azure api from 1.0.0 to 1.41.4

- .github/CODEOWNERS
- hostProviders/aws/pom.xml
- hostProviders/google/pom.xml
- hostProviders/google/src/main/java/com/ibm/spectrum/gcloud/client/GcloudClient.java
- hostProviders/oracle/README.md
> Merge10.1.0

- .gitignore
- hostProviders/ibmcloudgen2/requirements.txt
- hostProviders/ibmcloudgen2/scripts/nextgen_get_templates.py
- hostProviders/ibmcloudgen2/scripts/nextgen_rc_config.py
- hostProviders/ibmcloudgen2/scripts/vpc_vm_dns.py
**Feature**: Ability to spin dynamic compute hosts using catalog images.
Fixes #[4174](https://github.ibm.com/platformcomputing/lsf-tracker/issues/4174)
Enhancement - To spin the dynamic compute node, RC needs to support creating virtual servers using the images from catalog offering.
**IMPACT**: -- Provide an ability to spin dynamic compute hosts using catalog images.
NA
NA
NA
NA
When catalogOffering parameter in ibmcloudgen2_templates.json template file is set to
non-empty valid value, it should spin up the …
> IBM Cloud support for catalog images
